apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: simple-auth-baseline
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- api-keys.yaml
- routes.yaml
- auth-policy.yaml

commonLabels:
  component: simple-auth-baseline
  app.kubernetes.io/part-of: maas-benchmarking